// Game相關
export const INIT_GAME = 'INIT_GAME';
export const NEW_GAME = 'NEW_GAME';
export const UPDATE_GAME = 'UPDATE_GAME';

// Play相關
export const INIT_PLAY = 'INIT_PLAY';
export const UPDATE_GAMECODE = 'UPDATE_GAMECODE';
export const UPDATE_DRAGGING_CARDS = 'UPDATE_DRAGGING_CARDS';
export const RESET_DRAGGING_CARDS = 'RESET_DRAGGING_CARDS';
export const INCREASE_MOVES = 'INCREASE_MOVES';
export const RESET_MOVES = 'RESET_MOVES';
export const UPDATE_IS_GAME_STARTED = 'UPDATE_IS_GAME_STARTED';
export const ADD_HISTORY_MOVES = 'ADD_HISTORY_MOVES';
export const RESET_HISTORY_MOVES = 'RESET_HISTORY_MOVES';
export const POP_HISTORY_MOVES = 'POP_HISTORY_MOVES';
export const UPDATE_POSSIBLE_MOVE = 'UPDATE_POSSIBLE_MOVE';
